### ISSUE TITLE
NPM/Bower Dependency Manager for Composer

### ISSUE THREAD

**Issue by deizel** [gourmet/platform#2]
Not sure if you are aware of [composer-asset-plugin](https://github.com/francoispluchino/composer-asset-plugin#npmbower-dependency-manager-for-composer) yet, but this would eliminate having two commands for updating dependencies (`composer` and `bower`) as well as the requirement for Node.js.

Here is an example of how you use it:

``` javascript
    "require": {
        "fxp/composer-asset-plugin": "~1.0",
        "bower-asset/bootbox": "~4.3.0",
        "bower-asset/bootstrap-datepicker": "~1.3.0",
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "app/webroot/vendor",
            "bower-asset-library": "app/webroot/vendor"
        }
    }
```

.. and some output from Composer:

```
$ composer update --prefer-dist --optimize-autoloader
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing composer/installers (v1.0.21)
    Loading from cache

  - Installing fxp/composer-asset-plugin (v1.0.0)
    Loading from cache

  - Installing bower-asset/jquery (2.1.3)
    Loading from cache

  - Installing bower-asset/bootstrap (v3.3.2)
    Loading from cache

  - Installing bower-asset/bootbox (v4.3.0)
    Loading from cache
```

(Note: there is an alternative - [bowerphp](https://github.com/Bee-Lab/bowerphp) - but I didn't have much success with it on a larger project.)

**Comment by jadb** [comment]
Thanks @deizel - I was not aware of that, no. I have to admit I like adding automation  using composer or robo (which is included also in this custom app). I have one concern though.

I usually like vendor assets out of webroot and built (i.e. asset-compress or grunt), can I define one path like `ROOT/bower_components` where all assets are installed instead of just repeating like in the sample code above?

**Comment by deizel** [comment]
Unfortunately, it seems the location for NPM and Bower assets need [configured separately](https://github.com/francoispluchino/composer-asset-plugin/blob/1.0/Resources/doc/index.md#define-a-custom-directory-for-the-assets-installation), but if you are happy with the default locations below you won't need to configure those:
- `vendor/bower-asset/*`
- `vendor/npm-asset/*`

**Comment by jadb** [comment]
I actually like those even more than having them in the `ROOT` (less bloat). 

If you want, you can open a PR, otherwise I shall look into it some time soon. Keeping it open for now.

**Comment by deizel** [comment]
Well, it seems b131d8cdc66b4379214270c3d870c87eb35e8a93 is blocked until https://github.com/francoispluchino/composer-asset-plugin/issues/7 gets resolved. 

Composer doesn't download this list of dependencies in the correct order (ie. the plugin first).

```
$ composer create-project -s dev gourmet/platform:dev-composer-asset-plugin
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/bootstrap could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package bower-asset/jquery could not be found in any version, there may be a typo in the package name.
```

The only solution for the moment would be to update the readme as Yii have (https://github.com/yiisoft/yii2/commit/b6a53e3046edcdf5c93d27026ca0970da5aa5e88):

``` patch
+composer global require "fxp/composer-asset-plugin:~1.0"
 composer create-project -s dev gourmet/platform [app_name]
```

Of course, this would make installing the app template a two command process - is this something you would be prepared to live with if it meant removing the Bower/Node dependency?

**Comment by jadb** [comment]
Bummer!

PR seems open on Composer since July 2014 with no idea if it will ever get merged.

It's not having two commands (since it's already done using 2 right now) but relying on a globally installed package to install dependencies that irks me. 

Have you used this solution before? How well does it work in shared production environments?

**Comment by deizel** [comment]
Indeed it could take a while.. I also have a Composer PR that has been open for a similar amount of time.

> Have you used this solution before?

I haven't used this global approach for non-dev dependencies (ie. packages that need deployed in production). The projects I've used this on don't exhibit the issue so a `composer install` does the trick.

This might be because we don't include jQuery or Bootstrap directly, instead allowing Composer to infer their requirement through the dependency tree (e.g. `bootbox` requires `bootstrap`, requires `jquery`)

> How well does it work in shared production environments?

To be honest, I didn't even consider shared environments when leaving my last comment. I am aware that global packages are installed on a per-user basis (ie. to `~/.composer` on *nix), but I don't imagine this will be possible in most shared environments without changing `COMPOSER_HOME` (if Composer works at all).

**Comment by jadb** [comment]
Ok, so if I understood correctly, you build assets before deploying or during deployment (but not on server side).

In some cases, like heroku style deployments, it's better to build assets on the server and so certain dependencies (like frontend vendors) would be required, stored out of webroot and built during provisioning.

The current setup, despite using 2 commands (which this seems to suggest until the PR is merged), caters for both types of deploys - so I think, for now, better to keep.

I do however, as mentioned earlier, would love for that to become a one step, heck even 2 steps but everything under '/vendor' and managed by one package manager, so if you follow that thread, please keep me posted.

Leaving it open for now.

**Comment by deizel** [comment]
To clarify, we use the latter deployment style: clone on remote, composer install, asset compress, etc.

However, we don't use `composer global require` since we haven't hit this issue (yet).

Anyway, that doesn't really help us here - and I agree that both deployment styles should be supported.

I'm tracking multiple issues related to this so will keep you posted if there is any movement. :+1:
