### ISSUE TITLE
Re-think the configuration split for best of both worlds (prod/dev)

### ISSUE THREAD

**Issue by jadb** [gourmet/platform#7]
~~At the moment, and to make development easier, the application's configuration is broken into scopes.~~

~~This can however have some performance hits (and reason why the official app skeleton does not use it) since it needs to load all the files upfront. Instead, there should be a way to easily either load them as separate files or create concatenated version of all.~~

See https://github.com/gourmet/platform/issues/7#issuecomment-143416202 onward.

**Comment by phillaf** [comment]
Where does the performance hit comes from exactly? Could this be solved with a simple file_exists() in the bootstrap file, possibly mixed with caching to skip those calls once we know which config files are present?

**Comment by jadb** [comment]
Performance is affected from including multiple files. I remember @lorenzo mentioning that to me at one point and here's an [SO](http://stackoverflow.com/a/2298282) answer about it.

**Comment by lorenzo** [comment]
The hit comes usually from merging the configuration arrays

**Comment by jadb** [comment]
@lorenzo so keeping it in multiple files does not affect? I might have totally misunderstood the explanation you had given me for the core's app skeleton.

**Comment by lorenzo** [comment]
It does, but it is in the realm of he nanoseconds. What takes time is loading values into the Configure class, as it needs to merge the array every time

**Comment by jadb** [comment]
Thanks @lorenzo! 

Then I should have went the other way around, splitting stuff into files but getting them all loaded into `app.php`'s `array` basically getting the IDE fuzzy finder to jump to configurations really quickly (by topic, ie database, cache, etc.) without the hit of calling Configure multiple times.
